---
name: Build LCG on CVMFS

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Standard builds without sanitizers
          - release: "LCG_106"
            arch: "x86_64"
            os: "el9"
            compiler: "gcc13"
            opt: "opt"
          - release: "LCG_107"
            arch: "x86_64"
            os: "el9"
            compiler: "gcc14"
            opt: "opt"
          - release: "LCG_108"
            arch: "x86_64"
            os: "el9"
            compiler: "gcc15"
            opt: "opt"
          - release: "LCG_108"
            arch: "x86_64"
            os: "el9"
            compiler: "clang19"
            opt: "opt"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cvmfs-contrib/github-action-cvmfs@v3
        with:
          cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
      - uses: aidasoft/run-lcg-view@v1
        with:
          release-platform: ${{ matrix.release }}/${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.opt }}
          run: |
            echo "::group::Configuration"
            # Set BOOST_INC_DIR and BOOST_LIB_DIR to point to
            # LCG-provided Boost installation
            LCG_PATH="/cvmfs/sft.cern.ch/lcg/views/${{ matrix.release }}/${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.opt }}"
            export BOOST_INC_DIR="${LCG_PATH}/include"
            export BOOST_LIB_DIR="${LCG_PATH}/lib"

            # Generate setup scripts
            chmod +x SetupFiles/make_SET_ME_UP
            SetupFiles/make_SET_ME_UP
            echo "::endgroup::"

            echo "::group::Compilation of dependencies"
            # Build the dependencies
            # Note that postgresql fails in v0.65; see rbock/sqlpp11#623
            cmake -Bthirdparty/sqlpp11-build -Sthirdparty/sqlpp11/ \
              -DBUILD_MARIADB_CONNECTOR=ON \
              -DBUILD_MYSQL_CONNECTOR=ON \
              -DBUILD_POSTGRESQL_CONNECTOR=OFF \
              -DBUILD_SQLITE3_CONNECTOR=ON \
              -DCMAKE_INSTALL_PREFIX=thirdparty/sqlpp11-install
            cmake --build thirdparty/sqlpp11-build -j$(nproc) --target install
            export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:$PWD/thirdparty/sqlpp11-install
            echo "::endgroup::"

            echo "::group::Compilation of main project"
            # Build the project
            cmake -Bbuild -S.
            cmake --build build -j$(nproc)
            echo "::endgroup::"

            echo "::group::Mock data generation"
            # Run the mock data generator and analysis as described in README
            source SetupFiles/SET_ME_UP.bash
            
            # Generate mock data
            build/qwmockdatagenerator -r 4 -e 1:20000 \
              --config qwparity_simple.conf \
              --detectors mock_newdets.map \
              --data .
            echo "::endgroup::"

            echo "::group::Create database (sqlite3)"
            # Create and populate the database
            # (sqlite3 only supports AUTOINCREMENT on INTEGER keys)
            # (sqlite3 does not support ENUM, so convert to TEXT with CHECK)
            sed -e 's/AUTO_INCREMENT//g' \
                -e 's/\(\S*\)\sENUM(\([^)]*\))/\1 TEXT CHECK(\1 in (\2))/g' \
                Parity/prminput/qwparity_schema.sql | sqlite3 qwparity.db
            # Insert dummy schema version (compare with QwParityDB.h)
            sqlite3 qwparity.db "INSERT INTO db_schema VALUES(0, '01','04','0000','now','build-lcg-cvmfs.yml');"
            # Insert dummy seed data
            sqlite3 qwparity.db "INSERT INTO seeds VALUES(0, 0, 10, 'foo', 'bar');"
            echo "::endgroup::"

            echo "::group::Mock data analysis (sqlite3)"
            # Analyze the generated mock data
            build/qwparity -r 4 \
              --config qwparity_simple.conf \
              --detectors mock_newdets.map \
              --datahandlers mock_datahandlers.map \
              --data . \
              --rootfiles . \
              --write-promptsummary \
              --QwDatabase.accesslevel RW \
              --QwDatabase.dbtype sqlite3 \
              --QwDatabase.dbname qwparity.db
            echo "::endgroup::"

            echo "::group::Print database contents (sqlite3)"
            # Print the database contents
            sqlite3 qwparity.db .dump | tee qwparity-sqlite3.sql
            echo "::endgroup::"

      - name: Upload prompt summary
        uses: actions/upload-artifact@v4
        with:
          name: prompt-summary-${{ matrix.release }}-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.compiler }}
          path: |
            summary_*.txt
          retention-days: 7
          if-no-files-found: error

      - name: Upload database dumps
        uses: actions/upload-artifact@v4
        with:
          name: qwparity-sql-${{ matrix.release }}-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.compiler }}
          path: |
            qwparity-*.sql
          retention-days: 7
          if-no-files-found: error
